// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCHdV4CGZQDzEJjHf8h7INheBJKDBLp3I',
    appId: '1:51155040511:web:7f664cd3446e2ebad0f4ca',
    messagingSenderId: '51155040511',
    projectId: 'flutter-fin-96b59',
    authDomain: 'flutter-fin-96b59.firebaseapp.com',
    storageBucket: 'flutter-fin-96b59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9NLKo0W3oWAJA-cAuUcJkuRB_wulkxs',
    appId: '1:51155040511:android:c4c0652308b535c3d0f4ca',
    messagingSenderId: '51155040511',
    projectId: 'flutter-fin-96b59',
    storageBucket: 'flutter-fin-96b59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb6mSkNel_AN3C5SPFfDxIKJxqfbSW-P0',
    appId: '1:51155040511:ios:50a86a58cb55ce85d0f4ca',
    messagingSenderId: '51155040511',
    projectId: 'flutter-fin-96b59',
    storageBucket: 'flutter-fin-96b59.firebasestorage.app',
    iosBundleId: 'com.example.lastFinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb6mSkNel_AN3C5SPFfDxIKJxqfbSW-P0',
    appId: '1:51155040511:ios:50a86a58cb55ce85d0f4ca',
    messagingSenderId: '51155040511',
    projectId: 'flutter-fin-96b59',
    storageBucket: 'flutter-fin-96b59.firebasestorage.app',
    iosBundleId: 'com.example.lastFinapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCHdV4CGZQDzEJjHf8h7INheBJKDBLp3I',
    appId: '1:51155040511:web:ae7ea08d987c0599d0f4ca',
    messagingSenderId: '51155040511',
    projectId: 'flutter-fin-96b59',
    authDomain: 'flutter-fin-96b59.firebaseapp.com',
    storageBucket: 'flutter-fin-96b59.firebasestorage.app',
  );
}
